students/junius-sim/README.md

1) Very easy
2) Not sure 
3) Nope

Second forking was much better

---

students/zhiyin-ow/README.md

How difficult did you find this (out of 10)? 
- 6
Was there anything that you struggled with? 
- pushing to the correct origin
Is there anything that you'd like some further information on? -
Roughly, how long did it take? 10 minutes

add README

---

students/charles-guo/README.md

Please accept my request
- 6
- none because it was guided by Jesstern
- not at this time
- 10 mins

Adds my folder with its own README.md

---

students/jonathan-phoon/README.md

How difficult did you find this (out of 10)?
3!
Nope!
Not at the moment.
10mins?

Add Readme :smiley:

---

students/joanne-lo/README.md

7
Remembering the steps 
Flow of Git pull/push
2 hours

Adds README.txt

---

students/kt-khoo/README.md

How difficult did you find this (out of 10)? -> 2
Was there anything that you struggled with? -> not really
Is there anything that you'd like some further information on? -> N/A
Roughly, how long did it take? -> followed in class

add README.md

---

students/angeline-tan/README.md

0. How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible
..* 5
0. Was there anything that you struggled with?
..* No
0. Is there anything that you'd like some further information on?
..* what to put on the git hub page
0. Roughly, how long did it take?
..*

Create own folder and README in students folder.

---

students/melissa-kwek/readme.md

How difficult did you find this (out of 10)? 7
Was there anything that you struggled with? functions
Is there anything that you'd like some further information on? I need to practice more
Roughly, how long did it take? 18 hours for tic tac toe. 1 hour for stop watch.

Link to Homework (Melissa)

---

students/allan-lee/README.md

- 10 
- Still very unfamiliar with Javascript syntaxes
- probably need to read further and "inspect" similar projects to understand more
- probably 2 days after some help from fellow classmates.

allan's pull request

---

students/hakim-ariffin/README.md

Add README.md with name

---

students/david_tambu/README.md

7
updating the repo when i had already forked it
more details into the pull and push process
15mins

Forking review

---

README.md
students/stefanie-seah/README.md

Could you accept my pull request? I just made changes to the previous one.

Hello there

---

students/angeline-tan/README.md

Updated readme file to point to project repos.

Update README in student folder

---

students/joanne-lo/README.md

Adds homework links to README.txt 

---

students/charles-guo/README.md

Hi @jeremiahalex - my 2 projects currently do not show up correctly. Please accept this pull request for the 2 links to be correctly shown on the README.md file. thanks

updates links to the 2 github projects in README.md

---

students/firus-faizal/README.md

How difficult did you find this (out of 10)?
0 being no problems at all, 10 being impossible
- 8
- Syntax confusion with Javascript
- Video recordings of the lessons would be great, so that I can rewind/replay at my own time and pace
Half a day

Created the first README.md file as a means to test github connection

---

students/charles-guo/README.md

hi @jeremiahalex - please accept this change. thanks!

updates README with github link to js-calculator-lab

---

students/angeline-tan/README.md

Updates readme to include link to calculator app.

Updates readme to include link to calculator app.

---

students/zhiyin-ow/README.md

adds new lab - calculator with link

adds new lab - calculator with link

---

students/Joel-Yang/README.md

With the readme.md on master as well as google, it was a 2/10
Apparently I needed to auth my account/mac by using a hash key
took awhile to learn formatting for markdown but its a very simple functional language meant for readme as such there isn't much customization.

Creating GH Pages and README.md

---

students/siwei-kau/README.md

5
still getting used to closure and callbacks, not struggling but need more practise
-
did not manage to finish part of bonus

updated calculator

---

students/charles-guo/README.md

Hi @jeremiahalex - have added JQuery against the tictactoe since I have rewritten my script file in jQuery. I have also updated my README file with trello and added the link to Project 1. Please accept. Thanks!

updated README.md to indicate JQuery against tictactoe

---

students/firus-faizal/README.md

added links to Trello

---

students/stefanie-seah/README.md

New Readme File 

---

students/leoksi-koh/Readme.md

@jeremiahalex 
I have added Calculator link

added calculator links

---

students/stephanie-yeo/README.md

Putting in the missing links now. Sorry to be so slow.

README file update

---

students/charles-guo/README.md

updated README with project 4 links

---

students/junius-sim/README.md

Updated readme file with the 5pm codes. could not get heroku to work the second time.

updated readme file

---

students/Joel-Yang/README.md

Added link to project 2

---

students/leoksi-koh/Readme.md

@jeremiahalex @jsstrn @lanbau 
Project 2 completed

Edited Readme file
